amautas/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('offers.urls')),
    url(r'^admin/', admin.site.urls),
]

offers/urls.py
from django.conf.urls import url
from . import views

app_name = 'offers'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ofertas/(?P<job_id>[0-9]+)/$', views.show, name='show'),
    url(r'^ofertas/create/$', views.create, name='create'),
    url(r'^ofertas/store/$', views.store, name='store'),
]

offers/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Job(models.Model):
    title   = models.CharField(max_length=256)
    url     = models.URLField(max_length=512)
    body    = models.TextField()
    status  = models.BooleanField(default=1)

    def __str__(self):
        return self.title

offers/forms.py
from django import forms
from .models import Job

class OfferForm(forms.Form):
    title   = forms.CharField(label='Titulo',max_length=256)
    url     = forms.URLField(label='URL',max_length=512)
    body    = forms.CharField(label='Mensaje', widget=forms.Textarea)

    def save(self):
        data = self.cleaned_data
        job = Job()
        job.title   = data['title']
        job.url     = data['url']
        job.body    = data['body']
        return job.save()

offers/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Job
from .forms import OfferForm
# Create your views here.

# URL: ofertas/
def index(request):
    jobs = Job.objects.all()
    context = {'title':'Amautas', 'jobs':jobs}
    return render(request, 'offers/index.html', context)

# URL: ofertas/:job_id
def show(request, job_id):
    job = Job.objects.get(pk=job_id)
    context = {'job':job}
    return render(request, 'offers/show.html', context)

# URL: ofertas/create
def create(request):
    form = OfferForm()
    context = {
            'title':'Amautas',
            'form':form
        }

    return render(request, 'offers/create.html', context)

# URL: ofertas/store (method=POST)
def store(request):
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            context = {
                    'title':'Amautas',
                    'form':form
                }
            return render(request, 'offers/create.html', context)
    return HttpResponseRedirect('/ofertas/create')

# URL: ofertas/:job_id/edit
def edit(request):
    context = {'title':'Amautas'}
    return render(request, 'offers/edit.html', context)

# URL: ofertas/:job_id/update (method=POST)
def update(request):
    context = {'title':'Amautas'}
    return render(request, 'offers/update.html', context)

# URL: ofertas/:job_id/delete (method=POST)
def delete(request):
    context = {'title':'Amautas'}
    return render(request, 'offers/delete.html', context)

amautas/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>{{ title }}</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link rel="shortcut icon" href="images/favicon.png">

    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->
    {% load static %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'packages/material-design-lite/material.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/styles.css' %}">
  </head>
  <body>
    <div class="demo-blog mdl-layout mdl-js-layout has-drawer is-upgraded">
      <main class="mdl-layout__content">
        <div class="demo-blog__posts mdl-grid">

          <div class="mdl-card coffee-pic mdl-cell mdl-cell--8-col">
            <div class="mdl-card__media mdl-color-text--grey-50">
              <h3><a href="entry.html">{{ title }}</a></h3>
            </div>
            <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
              <div class="minilogo"></div>
              <div>
                {% block content %}{% endblock %}
              </div>
            </div>
          </div>

          <div class="mdl-card something-else mdl-cell mdl-cell--8-col mdl-cell--4-col-desktop">
            <a href="{% url 'offers:create' %}" class="mdl-button mdl-js-ripple-effect mdl-js-button mdl-button--fab mdl-color--accent">
              <i class="material-icons mdl-color-text--white" role="presentation">add</i>
              <span class="visuallyhidden">add</span>
            </a>
            <div class="mdl-card__media mdl-color--white mdl-color-text--grey-600">
              <img src="{% static 'assets/images/logo.png' %}">
              +1,337
            </div>
            <div class="mdl-card__supporting-text meta meta--fill mdl-color-text--grey-600">
              <div>
                <strong>The Newist</strong>
              </div>
              <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="menubtn">
                <li class="mdl-menu__item">About</li>
                <li class="mdl-menu__item">Message</li>
                <li class="mdl-menu__item">Favorite</li>
                <li class="mdl-menu__item">Search</li>
              </ul>
              <button id="menubtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                <i class="material-icons" role="presentation">more_vert</i>
                <span class="visuallyhidden">show menu</span>
              </button>
            </div>
          </div>

          {% for item in projects %}
            <div class="mdl-card on-the-road-again mdl-cell mdl-cell--12-col">
              <div class="mdl-card__media mdl-color-text--grey-50">
                <h3><a href="{{ item.url }}">{{ item.title }}</a></h3>
              </div>
              <div class="mdl-color-text--grey-600 mdl-card__supporting-text">
                <p>
                  Lenguaje de Programación: <strong>{{ item.prog_lang }}</strong><br>
                  Framework: <strong>{{ item.framework }}</strong>
                </p>
              </div>
              <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                <div class="minilogo"></div>
                <div>
                  <strong>{{ item.owner.lastname | upper}}, {{ item.owner.name }}</strong>
                  <span>{{ item.owner.cellphone }} | {{ item.owner.email }}</span>
                </div>
              </div>
            </div>
          {% endfor %}

        </div>
        {% include 'footer.html' %}
      </main>
      <div class="mdl-layout__obfuscator"></div>
    </div>
    <script src="{% static 'packages/material-design-lite/material.min.js' %}"></script>
  </body>
  <script>
    Array.prototype.forEach.call(document.querySelectorAll('.mdl-card__media'), function(el) {
      var link = el.querySelector('a');
      if(!link) {
        return;
      }
      var target = link.getAttribute('href');
      if(!target) {
        return;
      }
      el.addEventListener('click', function() {
        location.href = target;
      });
    });
  </script>
</html>

amautas/templates/footer.html
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer--left-section">
    <button class="mdl-mini-footer--social-btn social-btn social-btn__twitter">
      <span class="visuallyhidden">Twitter</span>
    </button>
    <button class="mdl-mini-footer--social-btn social-btn social-btn__blogger">
      <span class="visuallyhidden">Facebook</span>
    </button>
    <button class="mdl-mini-footer--social-btn social-btn social-btn__gplus">
      <span class="visuallyhidden">Google Plus</span>
    </button>
  </div>
  <div class="mdl-mini-footer--right-section">
    <button class="mdl-mini-footer--social-btn social-btn__share">
      <i class="material-icons" role="presentation">share</i>
      <span class="visuallyhidden">share</span>
    </button>
  </div>
</footer>

amautas/templates/offers/create.html
{% extends "base.html" %}

{% block content %}
<h3>Amautas | Crear oferta</h3>
<hr>
<form class="" action="{% url 'offers:store' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="Guardar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
</form>
{% endblock %}

amautas/templates/offers/index.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h1>{{ jobs|length }} Ofertas de trabajo</h1>
    <ul>
      {% for job in jobs %}
        <li><a href="{% url 'offers:show' job.id %}">{{ job.title }}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

amautas/templates/offers/show.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ job.title }}</h1>
<p>
  {{ job.body }}
</p>
{% endblock %}